Server:
  Modules:
    - ModuleName: Chat
      ModuleVersion: 1.0.0
      Address: 0.0.0.0
      Port: 8082
  Discovery:
    Consul:
      - Address: 127.0.0.1
        Port: 8500
    ConsulPath: /tframework
  Redis:
    Address: 192.168.1.82 #地址
    Port: 6382 #端口
    Password: #密码
    DB: 9 #db
  Gateway: false